stages:
  - test
  - build
  - deploy

variables:
  GIT_STRATEGY: clone

test_root:
  stage: test
  image: ubuntu:latest
  before_script:
    - apt update && apt install -y cmake g++
  script:
    - make test
  only:
    - main
    - library
    - app

build-doxygen:
  stage: build
  image: ubuntu:latest
  script:
    - apt-get update
    - apt-get install -y doxygen graphviz
    - cd library
    - doxygen Doxyfile
  artifacts:
    paths:
      - library/html/
    expire_in: 1 week
  only:
    - main
    - library
    - app

pages:
  stage: deploy
  script:
    - mv library/html public
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - main
    - library
    - app
