# TODO: Temporary disabled due to necessity of setting up Conan Center Index and automation for it

#name: CI
#
#on:
#  push:
#    branches:
#      - main
#      - dev
#  workflow_dispatch:
#  pull_request:
#    branches:
#      - main
#      - dev
#
#jobs:
#  build-and-test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#      - name: Install Python (for Conan)
#        uses: actions/setup-python@v4
#        with:
#          python-version: "3.13"
#      - name: Install Conan
#        run: |
#          pip install conan==2.12.1
#          conan --version
#      - name: Detect Conan profile
#        run:
#          cd library/
#          conan profile detect
#      - name: Configure Conan remote (optional)
#        # TODO add remote to secrets
#        run: |
#          conan remote add my-remote https://artifactory.example.com/artifactory/api/conan/conan-repo
#      - name: Login to Conan remote (optional)
#        # TODO add secrets
#        run: |
#          conan user -r my-remote -p "${{ secrets.CONAN_PASSWORD }}" "${{ secrets.CONAN_LOGIN_USERNAME }}"
#      - name: Build & create & publish with Makefile
#        # TODO get version from branch
#        run: |
#          make clean
#          make publish VERSION=1.0.0 USER=root CHANNEL=stable REMOTE=my-remote
