name: Build and Publish Doxygen

on:
  push:
    branches:
        - main
        - library
        - app
  pull_request:
    branches:
        - main
        - library
        - app
jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install Doxygen and Graphviz
        run: |
          apt-get update
          apt-get install -y doxygen graphviz

      - name: Generate documentation
        run: |
          cd library
          doxygen Doxyfile

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./library/html
