name: Library Tests

on:
  push:
    branches:
      - main
      - library
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - library

jobs:
  test-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:sumo/stable
          sudo apt-get update
          sudo apt-get install -y cmake g++ git libpugixml-dev git-lfs sumo sumo-tools sumo-doc
          git lfs pull

      - name: Run tests
        run: make test_library
